In [ ]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('diabetes.csv')

In [42]:
df.head()

Pregnancies  Glucose BloodPressure SkinThickness Insulin   BMI  \
0          6.0    148.0            72            35       0  33.6   
1          1.0     85.0            66            29       0  26.6   
2          8.0    183.0            64             0       0  23.3   
3          1.0     89.0            66            23      94  28.1   
4          0.0    137.0            40            35     168  43.1   

  DiabetesPedigreeFunction   Age Outcome  
0                    0.627  50.0       1  
1                    0.351  31.0       0  
2                    0.672  32.0       1  
3                    0.167  21.0       0  
4                    2.288  33.0       1

In [43]:
df.columns  

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [44]:
columns = ('Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome') 

for col in columns:
    print(col)
    print(df[col].unique()[:10])

Pregnancies
[ 6.  1.  8.  0.  5.  3. 10.  2.  4.  7.]
Glucose
[148.  85. 183.  89. 137. 116.  78. 115. 197. 125.]
BloodPressure
['72' '66' '64' '40' '74' '50' '0' '70' '96' '92']
SkinThickness
['35' '29' '0' '23' '32' '45' '19' '47' '38' nan]
Insulin
['0' '94' '168' '88' '543' '846' '175' '230' '83' '96']
BMI
['33.6' '26.6' '23.3' '28.1' '43.1' '25.6' '31' '35.3' '30.5' '0']
DiabetesPedigreeFunction
['0.627' '0.351' '0.672' '0.167' '2.288' '0.201' '0.248' '0.134' '0.158'
 nan]
Age
[50. 31. 32. 21. 33. 30. 26. 29. 53. 54.]
Outcome
['1' '0' nan '8jdj']


In [45]:
for col in columns:
    df[col] = pd.to_numeric(df[col], errors = 'coerce')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               781 non-null    float64
 1   Glucose                   777 non-null    float64
 2   BloodPressure             772 non-null    float64
 3   SkinThickness             762 non-null    float64
 4   Insulin                   766 non-null    float64
 5   BMI                       771 non-null    float64
 6   DiabetesPedigreeFunction  769 non-null    float64
 7   Age                       774 non-null    float64
 8   Outcome                   781 non-null    float64
dtypes: float64(9)
memory usage: 55.4 KB


In [47]:
df = df.dropna(subset = ['Outcome'])
df.reset_index(drop = True, inplace = True)

In [48]:
df.isnull().sum()

Pregnancies                  5
Glucose                      9
BloodPressure               14
SkinThickness               24
Insulin                     19
BMI                         15
DiabetesPedigreeFunction    17
Age                         12
Outcome                      0
dtype: int64

In [49]:
col_to_fix  = ('BloodPressure', 'SkinThickness', 'Insulin',
       'BMI') 

for col in col_to_fix:
    df[col] = df[col].replace(0, np.nan)

In [50]:
df.isnull().sum()

Pregnancies                   5
Glucose                       9
BloodPressure                49
SkinThickness               251
Insulin                     398
BMI                          26
DiabetesPedigreeFunction     17
Age                          12
Outcome                       0
dtype: int64

In [54]:
from sklearn.impute import SimpleImputer

fix_cols =  ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']

imputer = SimpleImputer(strategy = 'median')

df[fix_cols] = imputer.fit_transform(df[fix_cols])

df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64